Fix configure.ac.
Replace deprecated AC_PROG_INTLTOOL with IT_PROG_INTLTOOL.
Remove AM_GUN_GETTEXT, it conflicts with AM_GLIB_GNU_GETTEXT.

Without this change, `autoreconf` command fails to update po/Makefile.in.in correctly then `./configure` script fails with a message:

error: po/Makefile.in.in was not created by intltoolize.